
server: 
  port: 8010

docker:
  local:
    ip: 192.168.99.100
    
eureka: 
  client: 
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      
---
spring:
  profiles: localhost
  instance: 
    hostname: localhost 

      
---
spring:
  profiles: localdocker
eureka: 
  instance: 
    hostname: ${docker.local.ip} 

