server: 
  port: 8010

eureka: 
  client: 
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      
---
spring:
  profiles: localhost
  instance: 
    hostname: localhost 

      
---
spring:
  profiles: localdocker
eureka: 
  instance: 
    hostname: DOCKER 

